apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: CQBimRevitConnector
  title: "CQBimRevitConnector"
  namespace: saea
  description: Description of add-in here
  annotations:
    dev.azure.com/project-repo: SAEA/your-repo-here
spec:
  type: plugin
  owner: DKXXXX
  lifecycle: production
  productId: 641F5BA4-4AED-4AA3-8689-C5315BF469DF
  productOwner: DKXXXX
  actions:
    - name: Start